version: '3.8'

services:
  postgres-db:
    image: postgres:16.0
    restart: always
    # command: psql -U postgres -a -f /usr/src/dump.sql
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  fund-web:
    build: ./src
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      - DB=fund_manager
      - DB_USER=fastapi
      - DB_PASS=123456
      - DB_HOST=postgres-db
      - DB_PORT=5432
    depends_on:
      - postgres-db

volumes:
  postgres_data:
